val gl_version_1_1 : int
val gl_version_1_2 : int
val gl_false : int
val gl_true : int
val gl_byte : int
val gl_unsigned_byte : int
val gl_short : int
val gl_unsigned_short : int
val gl_int : int
val gl_unsigned_int : int
val gl_float : int
val gl_double : int
val gl_2_bytes : int
val gl_3_bytes : int
val gl_4_bytes : int
val gl_points : int
val gl_lines : int
val gl_line_loop : int
val gl_line_strip : int
val gl_triangles : int
val gl_triangle_strip : int
val gl_triangle_fan : int
val gl_quads : int
val gl_quad_strip : int
val gl_polygon : int
val gl_vertex_array : int
val gl_normal_array : int
val gl_color_array : int
val gl_index_array : int
val gl_texture_coord_array : int
val gl_edge_flag_array : int
val gl_vertex_array_size : int
val gl_vertex_array_type : int
val gl_vertex_array_stride : int
val gl_normal_array_type : int
val gl_normal_array_stride : int
val gl_color_array_size : int
val gl_color_array_type : int
val gl_color_array_stride : int
val gl_index_array_type : int
val gl_index_array_stride : int
val gl_texture_coord_array_size : int
val gl_texture_coord_array_type : int
val gl_texture_coord_array_stride : int
val gl_edge_flag_array_stride : int
val gl_vertex_array_pointer : int
val gl_normal_array_pointer : int
val gl_color_array_pointer : int
val gl_index_array_pointer : int
val gl_texture_coord_array_pointer : int
val gl_edge_flag_array_pointer : int
val gl_v2f : int
val gl_v3f : int
val gl_c4ub_v2f : int
val gl_c4ub_v3f : int
val gl_c3f_v3f : int
val gl_n3f_v3f : int
val gl_c4f_n3f_v3f : int
val gl_t2f_v3f : int
val gl_t4f_v4f : int
val gl_t2f_c4ub_v3f : int
val gl_t2f_c3f_v3f : int
val gl_t2f_n3f_v3f : int
val gl_t2f_c4f_n3f_v3f : int
val gl_t4f_c4f_n3f_v4f : int
val gl_matrix_mode : int
val gl_modelview : int
val gl_projection : int
val gl_texture : int
val gl_point_smooth : int
val gl_point_size : int
val gl_point_size_granularity : int
val gl_point_size_range : int
val gl_line_smooth : int
val gl_line_stipple : int
val gl_line_stipple_pattern : int
val gl_line_stipple_repeat : int
val gl_line_width : int
val gl_line_width_granularity : int
val gl_line_width_range : int
val gl_point : int
val gl_line : int
val gl_fill : int
val gl_cw : int
val gl_ccw : int
val gl_front : int
val gl_back : int
val gl_polygon_mode : int
val gl_polygon_smooth : int
val gl_polygon_stipple : int
val gl_edge_flag : int
val gl_cull_face : int
val gl_cull_face_mode : int
val gl_front_face : int
val gl_polygon_offset_factor : int
val gl_polygon_offset_units : int
val gl_polygon_offset_point : int
val gl_polygon_offset_line : int
val gl_polygon_offset_fill : int
val gl_compile : int
val gl_compile_and_execute : int
val gl_list_base : int
val gl_list_index : int
val gl_list_mode : int
val gl_never : int
val gl_less : int
val gl_equal : int
val gl_lequal : int
val gl_greater : int
val gl_notequal : int
val gl_gequal : int
val gl_always : int
val gl_depth_test : int
val gl_depth_bits : int
val gl_depth_clear_value : int
val gl_depth_func : int
val gl_depth_range : int
val gl_depth_writemask : int
val gl_depth_component : int
val gl_lighting : int
val gl_light0 : int
val gl_light1 : int
val gl_light2 : int
val gl_light3 : int
val gl_light4 : int
val gl_light5 : int
val gl_light6 : int
val gl_light7 : int
val gl_spot_exponent : int
val gl_spot_cutoff : int
val gl_constant_attenuation : int
val gl_linear_attenuation : int
val gl_quadratic_attenuation : int
val gl_ambient : int
val gl_diffuse : int
val gl_specular : int
val gl_shininess : int
val gl_emission : int
val gl_position : int
val gl_spot_direction : int
val gl_ambient_and_diffuse : int
val gl_color_indexes : int
val gl_light_model_two_side : int
val gl_light_model_local_viewer : int
val gl_light_model_ambient : int
val gl_front_and_back : int
val gl_shade_model : int
val gl_flat : int
val gl_smooth : int
val gl_color_material : int
val gl_color_material_face : int
val gl_color_material_parameter : int
val gl_normalize : int
val gl_clip_plane0 : int
val gl_clip_plane1 : int
val gl_clip_plane2 : int
val gl_clip_plane3 : int
val gl_clip_plane4 : int
val gl_clip_plane5 : int
val gl_accum_red_bits : int
val gl_accum_green_bits : int
val gl_accum_blue_bits : int
val gl_accum_alpha_bits : int
val gl_accum_clear_value : int
val gl_accum : int
val gl_add : int
val gl_load : int
val gl_mult : int
val gl_return : int
val gl_alpha_test : int
val gl_alpha_test_ref : int
val gl_alpha_test_func : int
val gl_blend : int
val gl_blend_src : int
val gl_blend_dst : int
val gl_zero : int
val gl_one : int
val gl_src_color : int
val gl_one_minus_src_color : int
val gl_dst_color : int
val gl_one_minus_dst_color : int
val gl_src_alpha : int
val gl_one_minus_src_alpha : int
val gl_dst_alpha : int
val gl_one_minus_dst_alpha : int
val gl_src_alpha_saturate : int
val gl_constant_color : int
val gl_one_minus_constant_color : int
val gl_constant_alpha : int
val gl_one_minus_constant_alpha : int
val gl_feedback : int
val gl_render : int
val gl_select : int
val gl_2d : int
val gl_3d : int
val gl_3d_color : int
val gl_3d_color_texture : int
val gl_4d_color_texture : int
val gl_point_token : int
val gl_line_token : int
val gl_line_reset_token : int
val gl_polygon_token : int
val gl_bitmap_token : int
val gl_draw_pixel_token : int
val gl_copy_pixel_token : int
val gl_pass_through_token : int
val gl_feedback_buffer_pointer : int
val gl_feedback_buffer_size : int
val gl_feedback_buffer_type : int
val gl_selection_buffer_pointer : int
val gl_selection_buffer_size : int
val gl_fog : int
val gl_fog_mode : int
val gl_fog_density : int
val gl_fog_color : int
val gl_fog_index : int
val gl_fog_start : int
val gl_fog_end : int
val gl_linear : int
val gl_exp : int
val gl_exp2 : int
val gl_logic_op : int
val gl_index_logic_op : int
val gl_color_logic_op : int
val gl_logic_op_mode : int
val gl_clear : int
val gl_set : int
val gl_copy : int
val gl_copy_inverted : int
val gl_noop : int
val gl_invert : int
val gl_and : int
val gl_nand : int
val gl_or : int
val gl_nor : int
val gl_xor : int
val gl_equiv : int
val gl_and_reverse : int
val gl_and_inverted : int
val gl_or_reverse : int
val gl_or_inverted : int
val gl_stencil_test : int
val gl_stencil_writemask : int
val gl_stencil_bits : int
val gl_stencil_func : int
val gl_stencil_value_mask : int
val gl_stencil_ref : int
val gl_stencil_fail : int
val gl_stencil_pass_depth_pass : int
val gl_stencil_pass_depth_fail : int
val gl_stencil_clear_value : int
val gl_stencil_index : int
val gl_keep : int
val gl_replace : int
val gl_incr : int
val gl_decr : int
val gl_none : int
val gl_left : int
val gl_right : int
val gl_front_left : int
val gl_front_right : int
val gl_back_left : int
val gl_back_right : int
val gl_aux0 : int
val gl_aux1 : int
val gl_aux2 : int
val gl_aux3 : int
val gl_color_index : int
val gl_red : int
val gl_green : int
val gl_blue : int
val gl_alpha : int
val gl_luminance : int
val gl_luminance_alpha : int
val gl_alpha_bits : int
val gl_red_bits : int
val gl_green_bits : int
val gl_blue_bits : int
val gl_index_bits : int
val gl_subpixel_bits : int
val gl_aux_buffers : int
val gl_read_buffer : int
val gl_draw_buffer : int
val gl_doublebuffer : int
val gl_stereo : int
val gl_bitmap : int
val gl_color : int
val gl_depth : int
val gl_stencil : int
val gl_dither : int
val gl_rgb : int
val gl_rgba : int
val gl_max_list_nesting : int
val gl_max_attrib_stack_depth : int
val gl_max_modelview_stack_depth : int
val gl_max_name_stack_depth : int
val gl_max_projection_stack_depth : int
val gl_max_texture_stack_depth : int
val gl_max_eval_order : int
val gl_max_lights : int
val gl_max_clip_planes : int
val gl_max_texture_size : int
val gl_max_pixel_map_table : int
val gl_max_viewport_dims : int
val gl_max_client_attrib_stack_depth : int
val gl_attrib_stack_depth : int
val gl_client_attrib_stack_depth : int
val gl_color_clear_value : int
val gl_color_writemask : int
val gl_current_index : int
val gl_current_color : int
val gl_current_normal : int
val gl_current_raster_color : int
val gl_current_raster_distance : int
val gl_current_raster_index : int
val gl_current_raster_position : int
val gl_current_raster_texture_coords : int
val gl_current_raster_position_valid : int
val gl_current_texture_coords : int
val gl_index_clear_value : int
val gl_index_mode : int
val gl_index_writemask : int
val gl_modelview_matrix : int
val gl_modelview_stack_depth : int
val gl_name_stack_depth : int
val gl_projection_matrix : int
val gl_projection_stack_depth : int
val gl_render_mode : int
val gl_rgba_mode : int
val gl_texture_matrix : int
val gl_texture_stack_depth : int
val gl_viewport : int
val gl_auto_normal : int
val gl_map1_color_4 : int
val gl_map1_grid_domain : int
val gl_map1_grid_segments : int
val gl_map1_index : int
val gl_map1_normal : int
val gl_map1_texture_coord_1 : int
val gl_map1_texture_coord_2 : int
val gl_map1_texture_coord_3 : int
val gl_map1_texture_coord_4 : int
val gl_map1_vertex_3 : int
val gl_map1_vertex_4 : int
val gl_map2_color_4 : int
val gl_map2_grid_domain : int
val gl_map2_grid_segments : int
val gl_map2_index : int
val gl_map2_normal : int
val gl_map2_texture_coord_1 : int
val gl_map2_texture_coord_2 : int
val gl_map2_texture_coord_3 : int
val gl_map2_texture_coord_4 : int
val gl_map2_vertex_3 : int
val gl_map2_vertex_4 : int
val gl_coeff : int
val gl_domain : int
val gl_order : int
val gl_fog_hint : int
val gl_line_smooth_hint : int
val gl_perspective_correction_hint : int
val gl_point_smooth_hint : int
val gl_polygon_smooth_hint : int
val gl_dont_care : int
val gl_fastest : int
val gl_nicest : int
val gl_scissor_test : int
val gl_scissor_box : int
val gl_map_color : int
val gl_map_stencil : int
val gl_index_shift : int
val gl_index_offset : int
val gl_red_scale : int
val gl_red_bias : int
val gl_green_scale : int
val gl_green_bias : int
val gl_blue_scale : int
val gl_blue_bias : int
val gl_alpha_scale : int
val gl_alpha_bias : int
val gl_depth_scale : int
val gl_depth_bias : int
val gl_pixel_map_s_to_s_size : int
val gl_pixel_map_i_to_i_size : int
val gl_pixel_map_i_to_r_size : int
val gl_pixel_map_i_to_g_size : int
val gl_pixel_map_i_to_b_size : int
val gl_pixel_map_i_to_a_size : int
val gl_pixel_map_r_to_r_size : int
val gl_pixel_map_g_to_g_size : int
val gl_pixel_map_b_to_b_size : int
val gl_pixel_map_a_to_a_size : int
val gl_pixel_map_s_to_s : int
val gl_pixel_map_i_to_i : int
val gl_pixel_map_i_to_r : int
val gl_pixel_map_i_to_g : int
val gl_pixel_map_i_to_b : int
val gl_pixel_map_i_to_a : int
val gl_pixel_map_r_to_r : int
val gl_pixel_map_g_to_g : int
val gl_pixel_map_b_to_b : int
val gl_pixel_map_a_to_a : int
val gl_pack_alignment : int
val gl_pack_lsb_first : int
val gl_pack_row_length : int
val gl_pack_skip_pixels : int
val gl_pack_skip_rows : int
val gl_pack_swap_bytes : int
val gl_unpack_alignment : int
val gl_unpack_lsb_first : int
val gl_unpack_row_length : int
val gl_unpack_skip_pixels : int
val gl_unpack_skip_rows : int
val gl_unpack_swap_bytes : int
val gl_zoom_x : int
val gl_zoom_y : int
val gl_texture_env : int
val gl_texture_env_mode : int
val gl_texture_1d : int
val gl_texture_2d : int
val gl_texture_wrap_s : int
val gl_texture_wrap_t : int
val gl_texture_mag_filter : int
val gl_texture_min_filter : int
val gl_texture_env_color : int
val gl_texture_gen_s : int
val gl_texture_gen_t : int
val gl_texture_gen_mode : int
val gl_texture_border_color : int
val gl_texture_width : int
val gl_texture_height : int
val gl_texture_border : int
val gl_texture_components : int
val gl_texture_red_size : int
val gl_texture_green_size : int
val gl_texture_blue_size : int
val gl_texture_alpha_size : int
val gl_texture_luminance_size : int
val gl_texture_intensity_size : int
val gl_nearest_mipmap_nearest : int
val gl_nearest_mipmap_linear : int
val gl_linear_mipmap_nearest : int
val gl_linear_mipmap_linear : int
val gl_object_linear : int
val gl_object_plane : int
val gl_eye_linear : int
val gl_eye_plane : int
val gl_sphere_map : int
val gl_decal : int
val gl_modulate : int
val gl_nearest : int
val gl_repeat : int
val gl_clamp : int
val gl_s : int
val gl_t : int
val gl_r : int
val gl_q : int
val gl_texture_gen_r : int
val gl_texture_gen_q : int
val gl_proxy_texture_1d : int
val gl_proxy_texture_2d : int
val gl_texture_priority : int
val gl_texture_resident : int
val gl_texture_binding_1d : int
val gl_texture_binding_2d : int
val gl_texture_internal_format : int
val gl_pack_skip_images : int
val gl_pack_image_height : int
val gl_unpack_skip_images : int
val gl_unpack_image_height : int
val gl_texture_3d : int
val gl_proxy_texture_3d : int
val gl_texture_depth : int
val gl_texture_wrap_r : int
val gl_max_3d_texture_size : int
val gl_texture_binding_3d : int
val gl_alpha4 : int
val gl_alpha8 : int
val gl_alpha12 : int
val gl_alpha16 : int
val gl_luminance4 : int
val gl_luminance8 : int
val gl_luminance12 : int
val gl_luminance16 : int
val gl_luminance4_alpha4 : int
val gl_luminance6_alpha2 : int
val gl_luminance8_alpha8 : int
val gl_luminance12_alpha4 : int
val gl_luminance12_alpha12 : int
val gl_luminance16_alpha16 : int
val gl_intensity : int
val gl_intensity4 : int
val gl_intensity8 : int
val gl_intensity12 : int
val gl_intensity16 : int
val gl_r3_g3_b2 : int
val gl_rgb4 : int
val gl_rgb5 : int
val gl_rgb8 : int
val gl_rgb10 : int
val gl_rgb12 : int
val gl_rgb16 : int
val gl_rgba2 : int
val gl_rgba4 : int
val gl_rgb5_a1 : int
val gl_rgba8 : int
val gl_rgb10_a2 : int
val gl_rgba12 : int
val gl_rgba16 : int
val gl_vendor : int
val gl_renderer : int
val gl_version : int
val gl_extensions : int
val gl_no_error : int
val gl_invalid_value : int
val gl_invalid_enum : int
val gl_invalid_operation : int
val gl_stack_overflow : int
val gl_stack_underflow : int
val gl_out_of_memory : int
val gl_rescale_normal : int
val gl_clamp_to_edge : int
val gl_max_elements_vertices : int
val gl_max_elements_indices : int
val gl_bgr : int
val gl_bgra : int
val gl_unsigned_byte_3_3_2 : int
val gl_unsigned_byte_2_3_3_rev : int
val gl_unsigned_short_5_6_5 : int
val gl_unsigned_short_5_6_5_rev : int
val gl_unsigned_short_4_4_4_4 : int
val gl_unsigned_short_4_4_4_4_rev : int
val gl_unsigned_short_5_5_5_1 : int
val gl_unsigned_short_1_5_5_5_rev : int
val gl_unsigned_int_8_8_8_8 : int
val gl_unsigned_int_8_8_8_8_rev : int
val gl_unsigned_int_10_10_10_2 : int
val gl_unsigned_int_2_10_10_10_rev : int
val gl_light_model_color_control : int
val gl_single_color : int
val gl_separate_specular_color : int
val gl_texture_min_lod : int
val gl_texture_max_lod : int
val gl_texture_base_level : int
val gl_texture_max_level : int
val gl_smooth_point_size_range : int
val gl_smooth_point_size_granularity : int
val gl_smooth_line_width_range : int
val gl_smooth_line_width_granularity : int
val gl_aliased_point_size_range : int
val gl_aliased_line_width_range : int
val gl_color_table : int
val gl_post_convolution_color_table : int
val gl_post_color_matrix_color_table : int
val gl_proxy_color_table : int
val gl_proxy_post_convolution_color_table : int
val gl_proxy_post_color_matrix_color_table : int
val gl_color_table_scale : int
val gl_color_table_bias : int
val gl_color_table_format : int
val gl_color_table_width : int
val gl_color_table_red_size : int
val gl_color_table_green_size : int
val gl_color_table_blue_size : int
val gl_color_table_alpha_size : int
val gl_color_table_luminance_size : int
val gl_color_table_intensity_size : int
val gl_convolution_1d : int
val gl_convolution_2d : int
val gl_separable_2d : int
val gl_convolution_border_mode : int
val gl_convolution_filter_scale : int
val gl_convolution_filter_bias : int
val gl_reduce : int
val gl_convolution_format : int
val gl_convolution_width : int
val gl_convolution_height : int
val gl_max_convolution_width : int
val gl_max_convolution_height : int
val gl_post_convolution_red_scale : int
val gl_post_convolution_green_scale : int
val gl_post_convolution_blue_scale : int
val gl_post_convolution_alpha_scale : int
val gl_post_convolution_red_bias : int
val gl_post_convolution_green_bias : int
val gl_post_convolution_blue_bias : int
val gl_post_convolution_alpha_bias : int
val gl_constant_border : int
val gl_replicate_border : int
val gl_convolution_border_color : int
val gl_color_matrix : int
val gl_color_matrix_stack_depth : int
val gl_max_color_matrix_stack_depth : int
val gl_post_color_matrix_red_scale : int
val gl_post_color_matrix_green_scale : int
val gl_post_color_matrix_blue_scale : int
val gl_post_color_matrix_alpha_scale : int
val gl_post_color_matrix_red_bias : int
val gl_post_color_matrix_green_bias : int
val gl_post_color_matrix_blue_bias : int
val gl_post_color_matrix_alpha_bias : int
val gl_histogram : int
val gl_proxy_histogram : int
val gl_histogram_width : int
val gl_histogram_format : int
val gl_histogram_red_size : int
val gl_histogram_green_size : int
val gl_histogram_blue_size : int
val gl_histogram_alpha_size : int
val gl_histogram_luminance_size : int
val gl_histogram_sink : int
val gl_minmax : int
val gl_minmax_format : int
val gl_minmax_sink : int
val gl_table_too_large : int
val gl_blend_equation : int
val gl_min : int
val gl_max : int
val gl_func_add : int
val gl_func_subtract : int
val gl_func_reverse_subtract : int
val gl_blend_color : int
val gl_current_bit : int
val gl_point_bit : int
val gl_line_bit : int
val gl_polygon_bit : int
val gl_polygon_stipple_bit : int
val gl_pixel_mode_bit : int
val gl_lighting_bit : int
val gl_fog_bit : int
val gl_depth_buffer_bit : int
val gl_accum_buffer_bit : int
val gl_stencil_buffer_bit : int
val gl_viewport_bit : int
val gl_transform_bit : int
val gl_enable_bit : int
val gl_color_buffer_bit : int
val gl_hint_bit : int
val gl_eval_bit : int
val gl_list_bit : int
val gl_texture_bit : int
val gl_scissor_bit : int
val gl_all_attrib_bits : int
val gl_client_pixel_store_bit : int
val gl_client_vertex_array_bit : int
val gl_all_client_attrib_bits : int
val gl_arb_multitexture : int
val gl_texture0_arb : int
val gl_texture1_arb : int
val gl_texture2_arb : int
val gl_texture3_arb : int
val gl_texture4_arb : int
val gl_texture5_arb : int
val gl_texture6_arb : int
val gl_texture7_arb : int
val gl_texture8_arb : int
val gl_texture9_arb : int
val gl_texture10_arb : int
val gl_texture11_arb : int
val gl_texture12_arb : int
val gl_texture13_arb : int
val gl_texture14_arb : int
val gl_texture15_arb : int
val gl_texture16_arb : int
val gl_texture17_arb : int
val gl_texture18_arb : int
val gl_texture19_arb : int
val gl_texture20_arb : int
val gl_texture21_arb : int
val gl_texture22_arb : int
val gl_texture23_arb : int
val gl_texture24_arb : int
val gl_texture25_arb : int
val gl_texture26_arb : int
val gl_texture27_arb : int
val gl_texture28_arb : int
val gl_texture29_arb : int
val gl_texture30_arb : int
val gl_texture31_arb : int
val gl_active_texture_arb : int
val gl_client_active_texture_arb : int
val gl_max_texture_units_arb : int
val gl_ext_abgr : int
val gl_abgr_ext : int
val gl_ext_blend_color : int
val gl_constant_color_ext : int
val gl_one_minus_constant_color_ext : int
val gl_constant_alpha_ext : int
val gl_one_minus_constant_alpha_ext : int
val gl_blend_color_ext : int
val gl_ext_polygon_offset : int
val gl_polygon_offset_ext : int
val gl_polygon_offset_factor_ext : int
val gl_polygon_offset_bias_ext : int
val gl_ext_texture3d : int
val gl_pack_skip_images_ext : int
val gl_pack_image_height_ext : int
val gl_unpack_skip_images_ext : int
val gl_unpack_image_height_ext : int
val gl_texture_3d_ext : int
val gl_proxy_texture_3d_ext : int
val gl_texture_depth_ext : int
val gl_texture_wrap_r_ext : int
val gl_max_3d_texture_size_ext : int
val gl_texture_3d_binding_ext : int
val gl_ext_texture_object : int
val gl_texture_priority_ext : int
val gl_texture_resident_ext : int
val gl_texture_1d_binding_ext : int
val gl_texture_2d_binding_ext : int
val gl_ext_rescale_normal : int
val gl_rescale_normal_ext : int
val gl_ext_vertex_array : int
val gl_vertex_array_ext : int
val gl_normal_array_ext : int
val gl_color_array_ext : int
val gl_index_array_ext : int
val gl_texture_coord_array_ext : int
val gl_edge_flag_array_ext : int
val gl_vertex_array_size_ext : int
val gl_vertex_array_type_ext : int
val gl_vertex_array_stride_ext : int
val gl_vertex_array_count_ext : int
val gl_normal_array_type_ext : int
val gl_normal_array_stride_ext : int
val gl_normal_array_count_ext : int
val gl_color_array_size_ext : int
val gl_color_array_type_ext : int
val gl_color_array_stride_ext : int
val gl_color_array_count_ext : int
val gl_index_array_type_ext : int
val gl_index_array_stride_ext : int
val gl_index_array_count_ext : int
val gl_texture_coord_array_size_ext : int
val gl_texture_coord_array_type_ext : int
val gl_texture_coord_array_stride_ext : int
val gl_texture_coord_array_count_ext : int
val gl_edge_flag_array_stride_ext : int
val gl_edge_flag_array_count_ext : int
val gl_vertex_array_pointer_ext : int
val gl_normal_array_pointer_ext : int
val gl_color_array_pointer_ext : int
val gl_index_array_pointer_ext : int
val gl_texture_coord_array_pointer_ext : int
val gl_edge_flag_array_pointer_ext : int
val gl_sgis_texture_edge_clamp : int
val gl_clamp_to_edge_sgis : int
val gl_ext_blend_minmax : int
val gl_func_add_ext : int
val gl_min_ext : int
val gl_max_ext : int
val gl_blend_equation_ext : int
val gl_ext_blend_subtract : int
val gl_func_subtract_ext : int
val gl_func_reverse_subtract_ext : int
val gl_ext_blend_logic_op : int
val gl_ext_point_parameters : int
val gl_point_size_min_ext : int
val gl_point_size_max_ext : int
val gl_point_fade_threshold_size_ext : int
val gl_distance_attenuation_ext : int
val gl_ext_paletted_texture : int
val gl_table_too_large_ext : int
val gl_color_table_format_ext : int
val gl_color_table_width_ext : int
val gl_color_table_red_size_ext : int
val gl_color_table_green_size_ext : int
val gl_color_table_blue_size_ext : int
val gl_color_table_alpha_size_ext : int
val gl_color_table_luminance_size_ext : int
val gl_color_table_intensity_size_ext : int
val gl_texture_index_size_ext : int
val gl_color_index1_ext : int
val gl_color_index2_ext : int
val gl_color_index4_ext : int
val gl_color_index8_ext : int
val gl_color_index12_ext : int
val gl_color_index16_ext : int
val gl_ext_clip_volume_hint : int
val gl_clip_volume_clipping_hint_ext : int
val gl_ext_compiled_vertex_array : int
val gl_array_element_lock_first_ext : int
val gl_array_element_lock_count_ext : int
val gl_hp_occlusion_test : int
val gl_occlusion_test_hp : int
val gl_occlusion_test_result_hp : int
val gl_ext_shared_texture_palette : int
val gl_shared_texture_palette_ext : int
val gl_ext_stencil_wrap : int
val gl_incr_wrap_ext : int
val gl_decr_wrap_ext : int
val gl_nv_texgen_reflection : int
val gl_normal_map_nv : int
val gl_reflection_map_nv : int
val gl_ext_texture_env_add : int
val gl_mesa_window_pos : int
val gl_mesa_resize_buffers : int
val gl_ext_texture_env_dot3 : int
val gl_dot3_rgb_ext : int
val gl_dot3_rgba_ext : int
