quote(mli, "val glu_ext_object_space_tess : int")
quote(mli, "val glu_ext_nurbs_tessellator : int")
quote(mli, "val glu_false : int")
quote(mli, "val glu_true : int")
quote(mli, "val glu_version_1_1 : int")
quote(mli, "val glu_version_1_2 : int")
quote(mli, "val glu_version_1_3 : int")
quote(mli, "val glu_version : int")
quote(mli, "val glu_extensions : int")
quote(mli, "val glu_invalid_enum : int")
quote(mli, "val glu_invalid_value : int")
quote(mli, "val glu_out_of_memory : int")
quote(mli, "val glu_invalid_operation : int")
quote(mli, "val glu_outline_polygon : int")
quote(mli, "val glu_outline_patch : int")
quote(mli, "val glu_nurbs_error : int")
quote(mli, "val glu_error : int")
quote(mli, "val glu_nurbs_begin : int")
quote(mli, "val glu_nurbs_begin_ext : int")
quote(mli, "val glu_nurbs_vertex : int")
quote(mli, "val glu_nurbs_vertex_ext : int")
quote(mli, "val glu_nurbs_normal : int")
quote(mli, "val glu_nurbs_normal_ext : int")
quote(mli, "val glu_nurbs_color : int")
quote(mli, "val glu_nurbs_color_ext : int")
quote(mli, "val glu_nurbs_texture_coord : int")
quote(mli, "val glu_nurbs_tex_coord_ext : int")
quote(mli, "val glu_nurbs_end : int")
quote(mli, "val glu_nurbs_end_ext : int")
quote(mli, "val glu_nurbs_begin_data : int")
quote(mli, "val glu_nurbs_begin_data_ext : int")
quote(mli, "val glu_nurbs_vertex_data : int")
quote(mli, "val glu_nurbs_vertex_data_ext : int")
quote(mli, "val glu_nurbs_normal_data : int")
quote(mli, "val glu_nurbs_normal_data_ext : int")
quote(mli, "val glu_nurbs_color_data : int")
quote(mli, "val glu_nurbs_color_data_ext : int")
quote(mli, "val glu_nurbs_texture_coord_data : int")
quote(mli, "val glu_nurbs_tex_coord_data_ext : int")
quote(mli, "val glu_nurbs_end_data : int")
quote(mli, "val glu_nurbs_end_data_ext : int")
quote(mli, "val glu_nurbs_error1 : int")
quote(mli, "val glu_nurbs_error2 : int")
quote(mli, "val glu_nurbs_error3 : int")
quote(mli, "val glu_nurbs_error4 : int")
quote(mli, "val glu_nurbs_error5 : int")
quote(mli, "val glu_nurbs_error6 : int")
quote(mli, "val glu_nurbs_error7 : int")
quote(mli, "val glu_nurbs_error8 : int")
quote(mli, "val glu_nurbs_error9 : int")
quote(mli, "val glu_nurbs_error10 : int")
quote(mli, "val glu_nurbs_error11 : int")
quote(mli, "val glu_nurbs_error12 : int")
quote(mli, "val glu_nurbs_error13 : int")
quote(mli, "val glu_nurbs_error14 : int")
quote(mli, "val glu_nurbs_error15 : int")
quote(mli, "val glu_nurbs_error16 : int")
quote(mli, "val glu_nurbs_error17 : int")
quote(mli, "val glu_nurbs_error18 : int")
quote(mli, "val glu_nurbs_error19 : int")
quote(mli, "val glu_nurbs_error20 : int")
quote(mli, "val glu_nurbs_error21 : int")
quote(mli, "val glu_nurbs_error22 : int")
quote(mli, "val glu_nurbs_error23 : int")
quote(mli, "val glu_nurbs_error24 : int")
quote(mli, "val glu_nurbs_error25 : int")
quote(mli, "val glu_nurbs_error26 : int")
quote(mli, "val glu_nurbs_error27 : int")
quote(mli, "val glu_nurbs_error28 : int")
quote(mli, "val glu_nurbs_error29 : int")
quote(mli, "val glu_nurbs_error30 : int")
quote(mli, "val glu_nurbs_error31 : int")
quote(mli, "val glu_nurbs_error32 : int")
quote(mli, "val glu_nurbs_error33 : int")
quote(mli, "val glu_nurbs_error34 : int")
quote(mli, "val glu_nurbs_error35 : int")
quote(mli, "val glu_nurbs_error36 : int")
quote(mli, "val glu_nurbs_error37 : int")
quote(mli, "val glu_auto_load_matrix : int")
quote(mli, "val glu_culling : int")
quote(mli, "val glu_sampling_tolerance : int")
quote(mli, "val glu_display_mode : int")
quote(mli, "val glu_parametric_tolerance : int")
quote(mli, "val glu_sampling_method : int")
quote(mli, "val glu_u_step : int")
quote(mli, "val glu_v_step : int")
quote(mli, "val glu_nurbs_mode : int")
quote(mli, "val glu_nurbs_mode_ext : int")
quote(mli, "val glu_nurbs_tessellator : int")
quote(mli, "val glu_nurbs_tessellator_ext : int")
quote(mli, "val glu_nurbs_renderer : int")
quote(mli, "val glu_nurbs_renderer_ext : int")
quote(mli, "val glu_object_parametric_error : int")
quote(mli, "val glu_object_parametric_error_ext : int")
quote(mli, "val glu_object_path_length : int")
quote(mli, "val glu_object_path_length_ext : int")
quote(mli, "val glu_path_length : int")
quote(mli, "val glu_parametric_error : int")
quote(mli, "val glu_domain_distance : int")
quote(mli, "val glu_map1_trim_2 : int")
quote(mli, "val glu_map1_trim_3 : int")
quote(mli, "val glu_point : int")
quote(mli, "val glu_line : int")
quote(mli, "val glu_fill : int")
quote(mli, "val glu_silhouette : int")
quote(mli, "val glu_smooth : int")
quote(mli, "val glu_flat : int")
quote(mli, "val glu_none : int")
quote(mli, "val glu_outside : int")
quote(mli, "val glu_inside : int")
quote(mli, "val glu_tess_begin : int")
quote(mli, "val glu_begin : int")
quote(mli, "val glu_tess_vertex : int")
quote(mli, "val glu_vertex : int")
quote(mli, "val glu_tess_end : int")
quote(mli, "val glu_end : int")
quote(mli, "val glu_tess_error : int")
quote(mli, "val glu_tess_edge_flag : int")
quote(mli, "val glu_edge_flag : int")
quote(mli, "val glu_tess_combine : int")
quote(mli, "val glu_tess_begin_data : int")
quote(mli, "val glu_tess_vertex_data : int")
quote(mli, "val glu_tess_end_data : int")
quote(mli, "val glu_tess_error_data : int")
quote(mli, "val glu_tess_edge_flag_data : int")
quote(mli, "val glu_tess_combine_data : int")
quote(mli, "val glu_cw : int")
quote(mli, "val glu_ccw : int")
quote(mli, "val glu_interior : int")
quote(mli, "val glu_exterior : int")
quote(mli, "val glu_unknown : int")
quote(mli, "val glu_tess_winding_rule : int")
quote(mli, "val glu_tess_boundary_only : int")
quote(mli, "val glu_tess_tolerance : int")
quote(mli, "val glu_tess_error1 : int")
quote(mli, "val glu_tess_error2 : int")
quote(mli, "val glu_tess_error3 : int")
quote(mli, "val glu_tess_error4 : int")
quote(mli, "val glu_tess_error5 : int")
quote(mli, "val glu_tess_error6 : int")
quote(mli, "val glu_tess_error7 : int")
quote(mli, "val glu_tess_error8 : int")
quote(mli, "val glu_tess_missing_begin_polygon : int")
quote(mli, "val glu_tess_missing_begin_contour : int")
quote(mli, "val glu_tess_missing_end_polygon : int")
quote(mli, "val glu_tess_missing_end_contour : int")
quote(mli, "val glu_tess_coord_too_large : int")
quote(mli, "val glu_tess_need_combine_callback : int")
quote(mli, "val glu_tess_winding_odd : int")
quote(mli, "val glu_tess_winding_nonzero : int")
quote(mli, "val glu_tess_winding_positive : int")
quote(mli, "val glu_tess_winding_negative : int")
quote(mli, "val glu_tess_winding_abs_geq_two : int")
quote(mli, "val glu_tess_max_coord : float")
quote(ml, "let glu_ext_object_space_tess = 1;;")
quote(ml, "let glu_ext_nurbs_tessellator = 1;;")
quote(ml, "let glu_false = 0;;")
quote(ml, "let glu_true = 1;;")
quote(ml, "let glu_version_1_1 = 1;;")
quote(ml, "let glu_version_1_2 = 1;;")
quote(ml, "let glu_version_1_3 = 1;;")
quote(ml, "let glu_version = 100800;;")
quote(ml, "let glu_extensions = 100801;;")
quote(ml, "let glu_invalid_enum = 100900;;")
quote(ml, "let glu_invalid_value = 100901;;")
quote(ml, "let glu_out_of_memory = 100902;;")
quote(ml, "let glu_invalid_operation = 100904;;")
quote(ml, "let glu_outline_polygon = 100240;;")
quote(ml, "let glu_outline_patch = 100241;;")
quote(ml, "let glu_nurbs_error = 100103;;")
quote(ml, "let glu_error = 100103;;")
quote(ml, "let glu_nurbs_begin = 100164;;")
quote(ml, "let glu_nurbs_begin_ext = 100164;;")
quote(ml, "let glu_nurbs_vertex = 100165;;")
quote(ml, "let glu_nurbs_vertex_ext = 100165;;")
quote(ml, "let glu_nurbs_normal = 100166;;")
quote(ml, "let glu_nurbs_normal_ext = 100166;;")
quote(ml, "let glu_nurbs_color = 100167;;")
quote(ml, "let glu_nurbs_color_ext = 100167;;")
quote(ml, "let glu_nurbs_texture_coord = 100168;;")
quote(ml, "let glu_nurbs_tex_coord_ext = 100168;;")
quote(ml, "let glu_nurbs_end = 100169;;")
quote(ml, "let glu_nurbs_end_ext = 100169;;")
quote(ml, "let glu_nurbs_begin_data = 100170;;")
quote(ml, "let glu_nurbs_begin_data_ext = 100170;;")
quote(ml, "let glu_nurbs_vertex_data = 100171;;")
quote(ml, "let glu_nurbs_vertex_data_ext = 100171;;")
quote(ml, "let glu_nurbs_normal_data = 100172;;")
quote(ml, "let glu_nurbs_normal_data_ext = 100172;;")
quote(ml, "let glu_nurbs_color_data = 100173;;")
quote(ml, "let glu_nurbs_color_data_ext = 100173;;")
quote(ml, "let glu_nurbs_texture_coord_data = 100174;;")
quote(ml, "let glu_nurbs_tex_coord_data_ext = 100174;;")
quote(ml, "let glu_nurbs_end_data = 100175;;")
quote(ml, "let glu_nurbs_end_data_ext = 100175;;")
quote(ml, "let glu_nurbs_error1 = 100251;;")
quote(ml, "let glu_nurbs_error2 = 100252;;")
quote(ml, "let glu_nurbs_error3 = 100253;;")
quote(ml, "let glu_nurbs_error4 = 100254;;")
quote(ml, "let glu_nurbs_error5 = 100255;;")
quote(ml, "let glu_nurbs_error6 = 100256;;")
quote(ml, "let glu_nurbs_error7 = 100257;;")
quote(ml, "let glu_nurbs_error8 = 100258;;")
quote(ml, "let glu_nurbs_error9 = 100259;;")
quote(ml, "let glu_nurbs_error10 = 100260;;")
quote(ml, "let glu_nurbs_error11 = 100261;;")
quote(ml, "let glu_nurbs_error12 = 100262;;")
quote(ml, "let glu_nurbs_error13 = 100263;;")
quote(ml, "let glu_nurbs_error14 = 100264;;")
quote(ml, "let glu_nurbs_error15 = 100265;;")
quote(ml, "let glu_nurbs_error16 = 100266;;")
quote(ml, "let glu_nurbs_error17 = 100267;;")
quote(ml, "let glu_nurbs_error18 = 100268;;")
quote(ml, "let glu_nurbs_error19 = 100269;;")
quote(ml, "let glu_nurbs_error20 = 100270;;")
quote(ml, "let glu_nurbs_error21 = 100271;;")
quote(ml, "let glu_nurbs_error22 = 100272;;")
quote(ml, "let glu_nurbs_error23 = 100273;;")
quote(ml, "let glu_nurbs_error24 = 100274;;")
quote(ml, "let glu_nurbs_error25 = 100275;;")
quote(ml, "let glu_nurbs_error26 = 100276;;")
quote(ml, "let glu_nurbs_error27 = 100277;;")
quote(ml, "let glu_nurbs_error28 = 100278;;")
quote(ml, "let glu_nurbs_error29 = 100279;;")
quote(ml, "let glu_nurbs_error30 = 100280;;")
quote(ml, "let glu_nurbs_error31 = 100281;;")
quote(ml, "let glu_nurbs_error32 = 100282;;")
quote(ml, "let glu_nurbs_error33 = 100283;;")
quote(ml, "let glu_nurbs_error34 = 100284;;")
quote(ml, "let glu_nurbs_error35 = 100285;;")
quote(ml, "let glu_nurbs_error36 = 100286;;")
quote(ml, "let glu_nurbs_error37 = 100287;;")
quote(ml, "let glu_auto_load_matrix = 100200;;")
quote(ml, "let glu_culling = 100201;;")
quote(ml, "let glu_sampling_tolerance = 100203;;")
quote(ml, "let glu_display_mode = 100204;;")
quote(ml, "let glu_parametric_tolerance = 100202;;")
quote(ml, "let glu_sampling_method = 100205;;")
quote(ml, "let glu_u_step = 100206;;")
quote(ml, "let glu_v_step = 100207;;")
quote(ml, "let glu_nurbs_mode = 100160;;")
quote(ml, "let glu_nurbs_mode_ext = 100160;;")
quote(ml, "let glu_nurbs_tessellator = 100161;;")
quote(ml, "let glu_nurbs_tessellator_ext = 100161;;")
quote(ml, "let glu_nurbs_renderer = 100162;;")
quote(ml, "let glu_nurbs_renderer_ext = 100162;;")
quote(ml, "let glu_object_parametric_error = 100208;;")
quote(ml, "let glu_object_parametric_error_ext = 100208;;")
quote(ml, "let glu_object_path_length = 100209;;")
quote(ml, "let glu_object_path_length_ext = 100209;;")
quote(ml, "let glu_path_length = 100215;;")
quote(ml, "let glu_parametric_error = 100216;;")
quote(ml, "let glu_domain_distance = 100217;;")
quote(ml, "let glu_map1_trim_2 = 100210;;")
quote(ml, "let glu_map1_trim_3 = 100211;;")
quote(ml, "let glu_point = 100010;;")
quote(ml, "let glu_line = 100011;;")
quote(ml, "let glu_fill = 100012;;")
quote(ml, "let glu_silhouette = 100013;;")
quote(ml, "let glu_smooth = 100000;;")
quote(ml, "let glu_flat = 100001;;")
quote(ml, "let glu_none = 100002;;")
quote(ml, "let glu_outside = 100020;;")
quote(ml, "let glu_inside = 100021;;")
quote(ml, "let glu_tess_begin = 100100;;")
quote(ml, "let glu_begin = 100100;;")
quote(ml, "let glu_tess_vertex = 100101;;")
quote(ml, "let glu_vertex = 100101;;")
quote(ml, "let glu_tess_end = 100102;;")
quote(ml, "let glu_end = 100102;;")
quote(ml, "let glu_tess_error = 100103;;")
quote(ml, "let glu_tess_edge_flag = 100104;;")
quote(ml, "let glu_edge_flag = 100104;;")
quote(ml, "let glu_tess_combine = 100105;;")
quote(ml, "let glu_tess_begin_data = 100106;;")
quote(ml, "let glu_tess_vertex_data = 100107;;")
quote(ml, "let glu_tess_end_data = 100108;;")
quote(ml, "let glu_tess_error_data = 100109;;")
quote(ml, "let glu_tess_edge_flag_data = 100110;;")
quote(ml, "let glu_tess_combine_data = 100111;;")
quote(ml, "let glu_cw = 100120;;")
quote(ml, "let glu_ccw = 100121;;")
quote(ml, "let glu_interior = 100122;;")
quote(ml, "let glu_exterior = 100123;;")
quote(ml, "let glu_unknown = 100124;;")
quote(ml, "let glu_tess_winding_rule = 100140;;")
quote(ml, "let glu_tess_boundary_only = 100141;;")
quote(ml, "let glu_tess_tolerance = 100142;;")
quote(ml, "let glu_tess_error1 = 100151;;")
quote(ml, "let glu_tess_error2 = 100152;;")
quote(ml, "let glu_tess_error3 = 100153;;")
quote(ml, "let glu_tess_error4 = 100154;;")
quote(ml, "let glu_tess_error5 = 100155;;")
quote(ml, "let glu_tess_error6 = 100156;;")
quote(ml, "let glu_tess_error7 = 100157;;")
quote(ml, "let glu_tess_error8 = 100158;;")
quote(ml, "let glu_tess_missing_begin_polygon = 100151;;")
quote(ml, "let glu_tess_missing_begin_contour = 100152;;")
quote(ml, "let glu_tess_missing_end_polygon = 100153;;")
quote(ml, "let glu_tess_missing_end_contour = 100154;;")
quote(ml, "let glu_tess_coord_too_large = 100155;;")
quote(ml, "let glu_tess_need_combine_callback = 100156;;")
quote(ml, "let glu_tess_winding_odd = 100130;;")
quote(ml, "let glu_tess_winding_nonzero = 100131;;")
quote(ml, "let glu_tess_winding_positive = 100132;;")
quote(ml, "let glu_tess_winding_negative = 100133;;")
quote(ml, "let glu_tess_winding_abs_geq_two = 100134;;")
quote(ml, "let glu_tess_max_coord = 1.0e150;;")
