val glu_ext_object_space_tess : int
val glu_ext_nurbs_tessellator : int
val glu_false : int
val glu_true : int
val glu_version_1_1 : int
val glu_version_1_2 : int
val glu_version_1_3 : int
val glu_version : int
val glu_extensions : int
val glu_invalid_enum : int
val glu_invalid_value : int
val glu_out_of_memory : int
val glu_invalid_operation : int
val glu_outline_polygon : int
val glu_outline_patch : int
val glu_nurbs_error : int
val glu_error : int
val glu_nurbs_begin : int
val glu_nurbs_begin_ext : int
val glu_nurbs_vertex : int
val glu_nurbs_vertex_ext : int
val glu_nurbs_normal : int
val glu_nurbs_normal_ext : int
val glu_nurbs_color : int
val glu_nurbs_color_ext : int
val glu_nurbs_texture_coord : int
val glu_nurbs_tex_coord_ext : int
val glu_nurbs_end : int
val glu_nurbs_end_ext : int
val glu_nurbs_begin_data : int
val glu_nurbs_begin_data_ext : int
val glu_nurbs_vertex_data : int
val glu_nurbs_vertex_data_ext : int
val glu_nurbs_normal_data : int
val glu_nurbs_normal_data_ext : int
val glu_nurbs_color_data : int
val glu_nurbs_color_data_ext : int
val glu_nurbs_texture_coord_data : int
val glu_nurbs_tex_coord_data_ext : int
val glu_nurbs_end_data : int
val glu_nurbs_end_data_ext : int
val glu_nurbs_error1 : int
val glu_nurbs_error2 : int
val glu_nurbs_error3 : int
val glu_nurbs_error4 : int
val glu_nurbs_error5 : int
val glu_nurbs_error6 : int
val glu_nurbs_error7 : int
val glu_nurbs_error8 : int
val glu_nurbs_error9 : int
val glu_nurbs_error10 : int
val glu_nurbs_error11 : int
val glu_nurbs_error12 : int
val glu_nurbs_error13 : int
val glu_nurbs_error14 : int
val glu_nurbs_error15 : int
val glu_nurbs_error16 : int
val glu_nurbs_error17 : int
val glu_nurbs_error18 : int
val glu_nurbs_error19 : int
val glu_nurbs_error20 : int
val glu_nurbs_error21 : int
val glu_nurbs_error22 : int
val glu_nurbs_error23 : int
val glu_nurbs_error24 : int
val glu_nurbs_error25 : int
val glu_nurbs_error26 : int
val glu_nurbs_error27 : int
val glu_nurbs_error28 : int
val glu_nurbs_error29 : int
val glu_nurbs_error30 : int
val glu_nurbs_error31 : int
val glu_nurbs_error32 : int
val glu_nurbs_error33 : int
val glu_nurbs_error34 : int
val glu_nurbs_error35 : int
val glu_nurbs_error36 : int
val glu_nurbs_error37 : int
val glu_auto_load_matrix : int
val glu_culling : int
val glu_sampling_tolerance : int
val glu_display_mode : int
val glu_parametric_tolerance : int
val glu_sampling_method : int
val glu_u_step : int
val glu_v_step : int
val glu_nurbs_mode : int
val glu_nurbs_mode_ext : int
val glu_nurbs_tessellator : int
val glu_nurbs_tessellator_ext : int
val glu_nurbs_renderer : int
val glu_nurbs_renderer_ext : int
val glu_object_parametric_error : int
val glu_object_parametric_error_ext : int
val glu_object_path_length : int
val glu_object_path_length_ext : int
val glu_path_length : int
val glu_parametric_error : int
val glu_domain_distance : int
val glu_map1_trim_2 : int
val glu_map1_trim_3 : int
val glu_point : int
val glu_line : int
val glu_fill : int
val glu_silhouette : int
val glu_smooth : int
val glu_flat : int
val glu_none : int
val glu_outside : int
val glu_inside : int
val glu_tess_begin : int
val glu_begin : int
val glu_tess_vertex : int
val glu_vertex : int
val glu_tess_end : int
val glu_end : int
val glu_tess_error : int
val glu_tess_edge_flag : int
val glu_edge_flag : int
val glu_tess_combine : int
val glu_tess_begin_data : int
val glu_tess_vertex_data : int
val glu_tess_end_data : int
val glu_tess_error_data : int
val glu_tess_edge_flag_data : int
val glu_tess_combine_data : int
val glu_cw : int
val glu_ccw : int
val glu_interior : int
val glu_exterior : int
val glu_unknown : int
val glu_tess_winding_rule : int
val glu_tess_boundary_only : int
val glu_tess_tolerance : int
val glu_tess_error1 : int
val glu_tess_error2 : int
val glu_tess_error3 : int
val glu_tess_error4 : int
val glu_tess_error5 : int
val glu_tess_error6 : int
val glu_tess_error7 : int
val glu_tess_error8 : int
val glu_tess_missing_begin_polygon : int
val glu_tess_missing_begin_contour : int
val glu_tess_missing_end_polygon : int
val glu_tess_missing_end_contour : int
val glu_tess_coord_too_large : int
val glu_tess_need_combine_callback : int
val glu_tess_winding_odd : int
val glu_tess_winding_nonzero : int
val glu_tess_winding_positive : int
val glu_tess_winding_negative : int
val glu_tess_winding_abs_geq_two : int
val glu_tess_max_coord : float
